# This is a default config file for bottom.  All of the settings are commented
# out by default; if you wish to change them uncomment and modify as you see
# fit.

# This group of options represents a command-line option.  Flags explicitly
# added when running (ie: btm -a) will override this config file if an option
# is also set here.
[flags]
# Whether to hide the average cpu entry.
hide_avg_cpu = true
# Whether to use dot markers rather than braille.
#dot_marker = false
# The update rate of the application.
#rate = "1s"
# Whether to put the CPU legend to the left.
#cpu_left_legend = false
# Whether to set CPU% on a process to be based on the total CPU or just current usage.
#current_usage = false
# Whether to set CPU% on a process to be based on the total CPU or per-core CPU% (not divided by the number of cpus).
#unnormalized_cpu = false
# Whether to group processes with the same name together by default.
group_processes = false
# Whether to make process searching case sensitive by default.
#case_sensitive = false
# Whether to make process searching look for matching the entire word by default.
#whole_word = false
# Whether to make process searching use regex by default.
#regex = false
# The temperature unit. One of the following, defaults to "c" for Celsius:
#temperature_type = "c"
##temperature_type = "k"
##temperature_type = "f"
##temperature_type = "kelvin"
##temperature_type = "fahrenheit"
##temperature_type = "celsius"
# The default time interval (in milliseconds).
#default_time_value = "60s"
# The time delta on each zoom in/out action (in milliseconds).
#time_delta = 15000
# Hides the time scale.
hide_time = true
# Override layout default widget
#default_widget_type = "proc"
#default_widget_count = 1
# Expand selected widget upon starting the app
#expanded = true
# Use basic mode
basic = true
# Use the old network legend style
#use_old_network_legend = false
# Remove space in tables
hide_table_gap = true
# Show the battery widgets
battery = true
# Disable mouse clicks
#disable_click = false
# Show memory values in the processes widget as values by default
#process_memory_as_value = false
# Show tree mode by default in the processes widget.
tree = true
# Shows an indicator in table widgets tracking where in the list you are.
#show_table_scroll_position = false
# Show processes as their commands by default in the process widget.
#process_command = false
# Displays the network widget with binary prefixes.
#network_use_binary_prefix = false
# Displays the network widget using bytes.
network_use_bytes = true
# Displays the network widget with a log scale.
#network_use_log = false
# Hides advanced options to stop a process on Unix-like systems.
#disable_advanced_kill = false
# Shows GPU(s) information
#enable_gpu = false
# Shows cache and buffer memory
#enable_cache_memory = false
# How much data is stored at once in terms of time.
#retention = "10m"
# Where to place the legend for the memory widget. One of "none", "top-left", "top", "top-right", "left", "right", "bottom-left", "bottom", "bottom-right".
memory_legend = "bottom-left"
# Where to place the legend for the network widget. One of "none", "top-left", "top", "top-right", "left", "right", "bottom-left", "bottom", "bottom-right".
network_legend = "bottom-left"

# Processes widget configuration
[processes]
# The columns shown by the process widget. The following columns are supported:
# PID, Name, CPU%, Mem%, R/s, W/s, T.Read, T.Write, User, State, Time, GMem%, GPU%
columns = ["PID", "Name", "CPU%", "Mem%", "GPU%", "Time", "State", "R/s", "W/s", "T.Read", "T.Write", "User", "GMem%"]

[styles.cpu]
all_entry_color = "white"
avg_entry_color = "white"
cpu_core_colors = ["white"]

[styles.memory]
ram_color = "white"
cache_color = "white"
swap_color = "white"
arc_color = "white"
gpu_colors = ["white"]

[styles.network]
rx_color = "white"
tx_color = "white"
rx_total_color = "white"
tx_total_color = "white"

[styles.tables]
headers = {color = "#ba0b0b", bold = true}

[styles.widgets]
selected_border_color = "#ba0b0b"
selected_text = {color = "black", bg_color = "#ba0b0b"}

[[row]]
  ratio=30
  [[row.child]]
  ratio=5
  type="cpu"
  [[row.child]]
  ratio=2
  type="batt"
[[row]]
    ratio=30
    [[row.child]]
      ratio=6
      type="temp"
    [[row.child]]
      ratio=5
      type="net"
[[row]]
  ratio=30
  [[row.child]]
    type="mem"
  [[row.child]]
    type="proc"
    default=true
