[accounts.gmail]
default = true
email = "ark.shaldov@gmail.com"
display-name = "Arkady Shaldov"
downloads-dir = "/home/ark/Downloads"
backend.type = "imap"
backend.root-dir = "/home/ark/mail"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "ark.shaldov@gmail.com"
backend.encryption.type = "tls"
backend.auth.type = "oauth2"
backend.auth.method = "xoauth2"
backend.auth.client-id = "1061903403886-s3f466119r7ms6pk2ul9j474l2673e6n.apps.googleusercontent.com"
backend.auth.auth-url = "https://accounts.google.com/o/oauth2/auth"
backend.auth.token-url = "https://www.googleapis.com/oauth2/v3/token"
backend.auth.pkce = true
backend.auth.redirect-scheme = "http"
backend.auth.redirect-host = "localhost"
backend.auth.redirect-port = 49152
backend.auth.scope = "https://mail.google.com/"
backend.auth.client-secret.keyring = "gmail-imap-oauth2-client-secret"
backend.auth.access-token.keyring = "gmail-imap-oauth2-access-token"
backend.auth.refresh-token.keyring = "gmail-imap-oauth2-refresh-token"
folder.aliases.trash = "[Gmail]/Trash"
folder.aliases.drafts = "[Gmail]/Drafts"
folder.aliases.inbox = "INBOX"
folder.aliases.sent = "[Gmail]/Sent Mail"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.login = "ark.shaldov@gmail.com"
message.send.backend.encryption.type = "tls"
message.send.backend.auth.type = "oauth2"
message.send.backend.auth.method = "xoauth2"
message.send.backend.auth.client-id = "1061903403886-s3f466119r7ms6pk2ul9j474l2673e6n.apps.googleusercontent.com"
message.send.backend.auth.auth-url = "https://accounts.google.com/o/oauth2/auth"
message.send.backend.auth.token-url = "https://www.googleapis.com/oauth2/v3/token"
message.send.backend.auth.pkce = true
message.send.backend.auth.redirect-scheme = "http"
message.send.backend.auth.redirect-host = "localhost"
message.send.backend.auth.redirect-port = 49152
message.send.backend.auth.scope = "https://mail.google.com/"
message.send.backend.auth.client-secret.keyring = "gmail-smtp-oauth2-client-secret"
message.send.backend.auth.access-token.keyring = "gmail-smtp-oauth2-access-token"
message.send.backend.auth.refresh-token.keyring = "gmail-smtp-oauth2-refresh-token"
