[default.files]
"nvim" = "~/.config/nvim"
"helix" = "~/.config/helix"
"clipse" = "~/.config/clipse"
"bottom.toml" = "~/.config/bottom/bottom.toml"
"dunstrc" = "~/.config/dunst/dunstrc"
"hypr" = "~/.config/hypr"
"kitty" = "~/.config/kitty"
"qutebrowser.py" = "~/.config/qutebrowser/config.py"
"sioyek" = "~/.config/sioyek"
"papis" = { target = "~/.config/papis", type = "symbolic" }
"wl-kbptr" = "~/.config/wl-kbptr"
"rofi/config.rasi" = "~/.config/rofi/config.rasi"
"rofi/theme.rasi" = "~/.config/rofi/themes/concrete.rasi"
"rofimoji.rc" = "~/.config/rofimoji.rc"
"rofi-rbw.rc" = "~/.config/rofi-rbw.rc"
"walker" = "~/.config/walker"
"waybar" = "~/.config/waybar"
"wob" = "~/.config/wob"
"systemd" = "~/.config/systemd/user"
"v2raya.json" = "~/.config/v2raya/current-config.json"
"tridactyl" = "~/.config/tridactyl"
"scripts" = "~/.local/bin"
"popups" = "~/.local/bin"
"keyd.conf" = "/etc/keyd/keyd.conf"
"kmonad" = "/etc/kmonad"
"logind.conf" = "/etc/systemd/logind.conf"
"ly/config.ini" = "/etc/ly/config.ini"
"fish" = "~/.config/fish"
"mimeapps.list" = "~/.config/mimeapps.list"
"applications" = "~/.local/share/applications/usr"

[default.variables]

color0 = "#fafafa"
color1 = "#bd4e46"
color2 = "#6fcc86"
color3 = "#bdb736"
color4 = "#5392bd"
color5 = "#b36b9d"
color6 = "#81d6cf"
color7 = "#2b2b2b"
color8 = "#fafafa"
color9 = "#bd4e46"
color10 = "#6fcc86"
color11 = "#bdb736"
color12 = "#5392bd"
color13 = "#b36b9d"
color14 = "#81d6cf"
color15 = "#2b2b2b"

